//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Organizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meeting_Organizer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Version.
        /// </summary>
        internal static string basicversion {
            get {
                return ResourceManager.GetString("basicversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Screen.
        /// </summary>
        internal static string blackscreen {
            get {
                return ResourceManager.GetString("blackscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to computer.
        /// </summary>
        internal static string button10 {
            get {
                return ResourceManager.GetString("button10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on screen.
        /// </summary>
        internal static string button11 {
            get {
                return ResourceManager.GetString("button11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to computer.
        /// </summary>
        internal static string button12 {
            get {
                return ResourceManager.GetString("button12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on screen.
        /// </summary>
        internal static string button13 {
            get {
                return ResourceManager.GetString("button13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string button14 {
            get {
                return ResourceManager.GetString("button14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to computer.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on screen.
        /// </summary>
        internal static string button3 {
            get {
                return ResourceManager.GetString("button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string button4 {
            get {
                return ResourceManager.GetString("button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string button5 {
            get {
                return ResourceManager.GetString("button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch image.
        /// </summary>
        internal static string button6 {
            get {
                return ResourceManager.GetString("button6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit image.
        /// </summary>
        internal static string button7 {
            get {
                return ResourceManager.GetString("button7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string button8 {
            get {
                return ResourceManager.GetString("button8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string button9 {
            get {
                return ResourceManager.GetString("button9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect T.V..
        /// </summary>
        internal static string connectthetv {
            get {
                return ResourceManager.GetString("connectthetv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying.
        /// </summary>
        internal static string displaying {
            get {
                return ResourceManager.GetString("displaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Version.
        /// </summary>
        internal static string freeversion {
            get {
                return ResourceManager.GetString("freeversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image #.
        /// </summary>
        internal static string imagenumber {
            get {
                return ResourceManager.GetString("imagenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit Meeting (Main Location).
        /// </summary>
        internal static string localmeetinglocation {
            get {
                return ResourceManager.GetString("localmeetinglocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Coordinator (Basic Edition).
        /// </summary>
        internal static string meetingcoordinatorbasic {
            get {
                return ResourceManager.GetString("meetingcoordinatorbasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Coordinator (Free Edition).
        /// </summary>
        internal static string meetingcoordinatorfree {
            get {
                return ResourceManager.GetString("meetingcoordinatorfree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Coordinator (Ultimate Edition).
        /// </summary>
        internal static string meetingcoordinatorultimate {
            get {
                return ResourceManager.GetString("meetingcoordinatorultimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Coordinator (Professional Edition).
        /// </summary>
        internal static string meetingcoordinatroprofessional {
            get {
                return ResourceManager.GetString("meetingcoordinatroprofessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not displaying on display.
        /// </summary>
        internal static string notdisplaying {
            get {
                return ResourceManager.GetString("notdisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a video, picture or connect to someone.
        /// </summary>
        internal static string opensomething {
            get {
                return ResourceManager.GetString("opensomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string preferences {
            get {
                return ResourceManager.GetString("preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Version.
        /// </summary>
        internal static string professionalversion {
            get {
                return ResourceManager.GetString("professionalversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Code.
        /// </summary>
        internal static string purchasecode {
            get {
                return ResourceManager.GetString("purchasecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve meeting (Remote Location).
        /// </summary>
        internal static string remotelocation {
            get {
                return ResourceManager.GetString("remotelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Restart.
        /// </summary>
        internal static string saveandrestart {
            get {
                return ResourceManager.GetString("saveandrestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string setup {
            get {
                return ResourceManager.GetString("setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No T.V. connected.
        /// </summary>
        internal static string thereisnotv {
            get {
                return ResourceManager.GetString("thereisnotv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate Version.
        /// </summary>
        internal static string ultimateversion {
            get {
                return ResourceManager.GetString("ultimateversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrades.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video is opened.
        /// </summary>
        internal static string videoopened {
            get {
                return ResourceManager.GetString("videoopened", resourceCulture);
            }
        }
    }
}
